name: install-rubygems

on:
  pull_request:

  push:
    branches:
      - master
      - 3.2

jobs:
  install_rubygems_ubuntu:
    name: Install Rubygems on Ubuntu (${{ matrix.ruby.name }}, ${{ matrix.openssl.name }})
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: 2.3, value: 2.3.8 }
          - { name: 2.4, value: 2.4.10 }
          - { name: 2.5, value: 2.5.8 }
          - { name: 2.6, value: 2.6.6 }
          - { name: 2.7, value: 2.7.2 }
          - { name: jruby-9.2, value: jruby-9.2.14.0 }
        openssl:
          - { name: "openssl", value: true }
          - { name: "no-openssl", value: false }
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install rubygems
        run: ruby -Ilib -S rake install 2> errors.txt
      - name: Check rubygems install produced no warnings
        run: test ! -s errors.txt || (cat errors.txt && exit 1)
      - name: Run a local rubygems command
        run: gem list bundler
        env:
          RUBYOPT: -Itest/rubygems/fake_certlib
        if: matrix.openssl.value == false
      - name: Run a local rubygems command
        run: gem list bundler
        if: matrix.openssl.value == true
      - name: Run a remote rubygems command
        run: gem outdated
        if: matrix.openssl.value == true
      - name: Run bundler installed as a default gem
        run: bundle --version
      - name: Check bundler man pages were installed and are properly picked up
        run: bundle install --help | grep -q BUNDLE-INSTALL
      - name: Check bundler fallback man pages are properly picked up
        run: sudo rm $(which man) && bundle install --help
      - name: Build bundler
        run: gem build bundler.gemspec
        working-directory: ./bundler
      - name: Install built bundler
        run: gem install bundler-*.gem --verbose > output.txt
        working-directory: ./bundler
      - name: Check bundler install didn't hit the network
        run: if grep -q 'GET http' output.txt; then false; else true; fi
        working-directory: ./bundler
      - name: Check rails can be installed
        run: gem install rails
    timeout-minutes: 10

  install_rubygems_windows:
    name: Install Rubygems on Windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler: none
      - name: Install rubygems
        run: ruby setup.rb
        shell: bash
      - name: Check installation didn't modify gemspec line feeds
        run: ruby -Ilib -e'exit 1 if File.readlines("bundler/bundler.gemspec").first.end_with?("\r\n")'
        shell: bash
    timeout-minutes: 10
