name: macos_rubygems

on:
  pull_request:

  push:
    branches:
      - master
      - 3.2

jobs:
  macos_rubygems:
    name: Rubygems on MacOS (${{ matrix.ruby.name }})
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: 2.4, value: 2.4.10 }
          - { name: 2.5, value: 2.5.8 }
          - { name: 2.6, value: 2.6.6 }
          - { name: 2.7, value: 2.7.2 }
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install Dependencies
        run: rake setup
      - name: Run Test
        run: rake test
    timeout-minutes: 15
