name: truffleruby-bundler

on:
  pull_request:

  push:
    branches:
      - master
      - 3.2

jobs:
  jruby_bundler:
    name: Bundler (Truffleruby)
    runs-on: ubuntu-20.04

    env:
      RGV: ..

    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: truffleruby-20.3.0
          bundler: none
      - name: Prepare dependencies
        run: |
          bin/rake spec:parallel_deps
        working-directory: ./bundler
      - name: Run Test
        run: |
          bin/parallel_rspec --tag truffleruby
        working-directory: ./bundler
