name: ubuntu-rubygems

on:
  pull_request:

  push:
    branches:
      - master
      - 3.2

jobs:
  ubuntu_rubygems:
    name: Rubygems on Ubuntu (${{ matrix.ruby.name }})
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: "2.3", value: 2.3.8 }
          - { name: "2.4", value: 2.4.10 }
          - { name: "2.5", value: 2.5.8 }
          - { name: "2.6", value: 2.6.6 }
          - { name: "2.7", value: 2.7.2 }
          - { name: "3.0", value: 3.0.0 }
          - { name: jruby-9.2, value: jruby-9.2.14.0 }
          - { name: truffleruby-20.3, value: truffleruby-20.3.0 }
    env:
      TRUFFLERUBYOPT: "--experimental-options --testing-rubygems"
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install Dependencies
        run: rake setup
      - name: Run Test
        run: rake test
    timeout-minutes: 60
