name: ubuntu-bundler

on:
  pull_request:

  push:
    branches:
      - master
      - 3.2

jobs:
  ubuntu_bundler:
    name: Bundler ${{ matrix.bundler.name }} (${{ matrix.ruby.name }})
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: ruby-2.3, value: 2.3.8 }
          - { name: ruby-2.4, value: 2.4.10 }
          - { name: ruby-2.5, value: 2.5.9 }
          - { name: ruby-2.6, value: 2.6.7 }
          - { name: ruby-2.7, value: 2.7.3 }
          - { name: ruby-3.0, value: 3.0.1 }

        bundler:
          - { name: 2, value: '' }
          - { name: 3, value: 3.0.0 }

        exclude:
          - { bundler: { name: 3, value: 3.0.0 }, ruby: { name: ruby-2.3, value: 2.3.8 } }
          - { bundler: { name: 3, value: 3.0.0 }, ruby: { name: ruby-2.4, value: 2.4.10 } }
          - { bundler: { name: 3, value: 3.0.0 }, ruby: { name: ruby-2.5, value: 2.5.9 } }
    env:
      RGV: ..
      RUBYOPT: --disable-gems
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install graphviz
        run: sudo apt-get install graphviz -y
        if: matrix.bundler.value == ''
      - name: Replace version
        run: BUNDLER_SPEC_SUB_VERSION=${{ matrix.bundler.value }} bin/rake override_version
        if: matrix.bundler.value != ''
        working-directory: ./bundler
      - name: Prepare dependencies
        run: |
          bin/rake spec:parallel_deps
        working-directory: ./bundler
      - name: Run Test
        run: |
          bin/rake spec:all
        working-directory: ./bundler
    timeout-minutes: 60
