name: windows-bundler

on:
  pull_request:

  push:
    branches:
      - master
      - 3.2

jobs:
  windows_bundler:
    name: Bundler on Windows (${{ matrix.ruby.name }})

    runs-on: windows-2019

    env:
      RGV: ..

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: jruby-9.2, value: jruby-9.2.16.0 }
          - { name: ruby-2.5, value: 2.5.9 }
          - { name: ruby-3.0, value: 3.0.1 }

    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install dependencies
        run: |
          bin/rake spec:parallel_deps
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: |
          bin/parallel_rspec
        working-directory: ./bundler
        shell: bash
        if: "!startsWith(matrix.ruby.name, 'jruby')"
